# Generated by Django 5.1.3 on 2024-11-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(max_length=250, verbose_name='Refresh token')),
                ('access_token', models.CharField(max_length=250, verbose_name='Access token')),
                ('client_id', models.CharField(max_length=250, verbose_name='Client id')),
                ('device_id', models.CharField(max_length=250, verbose_name='Device id')),
                ('state', models.CharField(max_length=250, verbose_name='State')),
                ('scope', models.CharField(max_length=250, verbose_name='Scope(список доступов)')),
                ('last_full_update', models.DateField(verbose_name='Дата последнего полного обновления')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
