# Generated by Django 5.1.3 on 2024-11-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VKstorage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='access_token',
            field=models.TextField(verbose_name='Access token'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='refresh_token',
            field=models.TextField(verbose_name='Refresh token'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='scope',
            field=models.CharField(max_length=250, verbose_name='Scope (список доступов)'),
        ),
    ]
