# Generated by Django 5.1.3 on 2024-11-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VKstorage', '0002_alter_settings_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='vkapi_version',
            field=models.CharField(default=5.199, max_length=250, verbose_name='Версия VK API'),
            preserve_default=False,
        ),
    ]
