# Generated by Django 5.1.3 on 2024-11-24 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VKstorage', '0003_settings_vkapi_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название группы')),
                ('group_id', models.CharField(max_length=250, verbose_name='Groups id')),
                ('short_name', models.CharField(max_length=250, verbose_name='Короткое имя')),
                ('last_update', models.DateField(verbose_name='Дата последнего полного информации о группе')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.CharField(max_length=250, verbose_name='Groups id')),
                ('start_date', models.CharField(max_length=250, verbose_name='Groups id')),
                ('story_type', models.CharField(max_length=250, verbose_name='Groups id')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VKstorage.groups')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
        ),
    ]
