# Generated by Django 5.1.3 on 2024-11-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VKstorage', '0004_groups_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='start_date',
            field=models.IntegerField(verbose_name='Дата и время публикации (Unix time)'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='story_id',
            field=models.CharField(max_length=250, verbose_name='Story id'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='story_type',
            field=models.CharField(max_length=250, verbose_name='Тип публикации'),
        ),
    ]
