# Generated by Django 5.1.3 on 2024-11-24 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VKstorage', '0005_alter_stories_start_date_alter_stories_story_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата и время публикации'),
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=250, verbose_name='Пост id')),
                ('start_date', models.DateTimeField(verbose_name='Дата и время публикации')),
                ('post_type', models.IntegerField(choices=[(1, 'Видео'), (2, 'Пост'), (3, 'Репост клипа'), (4, 'Статья')], verbose_name='Тип публикации')),
                ('likes', models.IntegerField(verbose_name='Лийки')),
                ('comments', models.IntegerField(verbose_name='Коментарии')),
                ('reposts', models.IntegerField(verbose_name='Репосты')),
                ('views', models.IntegerField(verbose_name='Просмотры')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VKstorage.groups')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
