# Generated by Django 5.1.3 on 2024-11-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VKstorage', '0006_alter_stories_start_date_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='text',
            field=models.CharField(default=123, max_length=250, verbose_name='Краткий текст поста'),
            preserve_default=False,
        ),
    ]
