# Generated by Django 5.1.3 on 2024-12-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VKstorage', '0009_settings_access_token_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='access_token_live',
        ),
    ]
